[package]
name = "vestflow-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
vestflow = { path = "..", features = ["fuzz"] }

[[bin]]
name = "stream_balance"
path = "fuzz_targets/stream_balance.rs"
test = false
doc = false

[[bin]]
name = "available_balance"
path = "fuzz_targets/available_balance.rs"
test = false
doc = false
