export { GET } from "./../../events"
export { POST } from "./../../events"
export { PUT } from "./../../events"
export { PATCH } from "./../../events"
export { DELETE } from "./../../events"
export { HEAD } from "./../../events"
